name: Jekyll site CI

on:
  push:
    branches:
      - master  # Adjust this to your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'  # Specifies Ruby 3.3.4

      - name: Install and Cache Gems
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build the Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./_site
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ 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 }}